# Python for Data Science
#### See 'Python Library.docx' for additional info

In [1]:
# import math module as m
import math as m

# import copy module
import copy

#import numpy as np
import numpy as np

#import pandas as pd
import pandas as pd

## Functions
- `int(data)` converts data to 'int' (truncates floats)
- `float(data)` converts data to 'float'
- `str(data)` converts data to string
- `max(data)` returns the maximum value
    - data could be values separated by commas or a list (see numpy for arrays)
- `round(num[, digits])` rounds number to specified digits (not decimal places) or 'int' by default

#### Math Module
- `import math as m`
- `m.pow(num, pow)` raises num to pow (num ** pow)
- `m.sqrt(num)` returns the square root of num
- `m.ceil(num)` rounds num up
- `m.floor(num)` rounds num down
- `m.pi` returns pi to 15 decimal places

## Lists
#### List Comprehensions
- Process lists without using for loops and increases efficiency by saving memory and time
- Works like any iterable
- `new_list = [var_statement for var in old_list]`
    - `var_statement` is your calculation or code to execute for each list item
    - `var_statement` should reference `var` which is assigned by you and represents each element
    - `old_list` is the original list
- `new_list = [statement_with_var1_var2 for var1 in list1 for var2 in list2]`
    - nested syntax
- `statement` is something to return
    - () would return a tuple
    - [] would return a list
    - can also do arithmetic or other math-like-stuff

#### List Operations to Remember
- Slicing
    - `list[start:end:step]` just like with numpy arrays
    - if start or stop is blank, starts at the beginning or goes to the end respectively
    - default step is 1
- Creating a Deep Copy
    - `copy.deepcopy(list)` outputs a copy of a list, not just another reference to it
- `len(list)`, `min(list)`, and `max(list)` all perform as expected
- Sorting
    - `sorted(list[, key=function])`
        - **returns a new list** sorted, with optional function to run before sorting
            - option function like `key=str.lower` does not affect values, just sort behavior
            - see .sort() method for rearranging a list
    - `list.sort([key=function])`
        - **modifies the current list** and sorts, based on optional function
        - default sort order in all cases is 0-9, A-Z, a-z
- `list.append(item)` adds item to the end of a list
- `list.remove(item)` removes item from the list
- `list.index(item)` returns the index for the item
- `list.pop([index])` removes and returns item at specified index (or last item by default)
- `list.count(item)` returns the number of occurrences of item in list or 0 if none
- `list.reverse()` reverses the order of items in the list

## Dictionaries
- Checking if a key exists
    - `if key in dictionary:`
- Deleting items
    - `del dictionary['key']
    - `dictionary.pop['key'[, default_value]]
        - these throw errors if 'key' doesn't exist, or will return a 'default_value'
    - `dictionary.clear()` deletes all dictionary items
- `dictionary.get(key[, default_value])`
    - returns the value associated with key, or default_value if specified and key doesn't exist
    - works like `dictionary[key]` except you can specify default value
- `dictionary.keys()`
    - returns a view object of all the keys (**default iterator for a dictionary**)
- `dictionary.items()`
    - returns a view object containing a tuple of each key/value pair
- `dictionary.values()`
    - returns a view object containing all of the values
    
#### Looping Through Dictionaries
- Need an iterator obtained using the `.keys()`, `.items()`, or `.values()` methods
- `for key in dictionary.keys():`
    - `statements with dictionary[key]`
- `for key, value in dictionary.items():`
    - `statements using key and value`
- `for value in dictionary.values()`
    - `statements using value

## Formatting Numbers as Strings
- Used for display or converting numbers to strings
- `"{:format_specification}".format(data)` formats supplied `data` to `:format_specification`
- It is possible to pass mulitple format specifications and multiple data entries/types
    - `"{:form_spec1}{:form_spec2}{form_spec3}".format("str", float, int)
    - can print grid if doing multiple times using consistent `field_width` in each position
- format_sepcification is comprised of:
    - `[field_width][,][.decimal_places][type_code]`
    - `field_width` is specified in pixels as 'int'
        - by default, strings are justified left and numbers justified right
        - add `>` or `<` just before pixels to specify 'right' and 'left' justified
    - `,` specifies whether large numbers use commas
    - `.decimal_places` dot with number of decimal places to include
    - `type_code` specifies data type
        - `d` integer (decimals can't be specified)
        - `f` float (will round to specified decimal places)
        - `%` percent (supply decimal, it multiplies by 100 and adds '%'
        - `e` converted to scientific notation

In [2]:
# format grid example
heads = ["item", "price", "qty"]
x = ["hammer", 9.99, 11]
y = ["nails", 1.99, 24]
print("{:15}{:>8}{:>8}".format(heads[0], heads[1], heads[2]))
print("{:15}{:8.2f}{:8d}".format(x[0], x[1], x[2]))
print("{:15}{:8.2f}{:8d}".format(y[0], y[1], y[2]))

item              price     qty
hammer             9.99      11
nails              1.99      24


## Program Structure
#### Shebang
- `#!/usr/bin/env python3`
    - first line of a .py file
    - ignored by Windows but used by Unix-like systems to use correct interpreter

#### Three-Tier Approach
- Good practice when writing a program to use three tier approach
- Main function
    - starts an application, but is defined last
    - `def main:` with code to execute the app
    - `if __name__ == '__main__':
        - `main()`
- UI Tier
    - User interface
    - Contains the `__main__` function
    - Console app is usually procedural code vs GUI which is object-oriented
- Business or Object Tier
    - Processing tier
    - OOP to work with classes/objects and data from a database
- Database Tier
    - Provide database access

## Iterables and Looping
#### Iterators and Iterables
- Iterator is any object with an `iter()` method
    - lists, strings, dictionaries, etc.
    - Use `next()` to iterate through the object
    - Access all (remaining) values at once using `next(*var)`

In [3]:
# create the iterable object
# use next to iterate
# throws StopIteration Error when out of values
var = iter([1, 2, 3, 4, 5, 6])
print(next(var))
print(next(var))
print([next(var), next(var), next(var), next(var)])
print(next(var)) # throws exception because out of values!

1
2
[3, 4, 5, 6]


StopIteration: 

#### Zip Objects
- `zip(iterables)` iterables separated by commas
    - zipping will take two or more iterables (such as lists) and stitch them together
    - it matches values at the same index and combines into a tuple
        - you end up with a zip object containing tuples
        - the tuple at index 0 contains all of the index 0 values
    - convert to a list using `list(zip_obj)`
    - convert to a dictionary using `dict(zip_obj)`

#### Iterating Through a File
- `with open('file.txt') as file:`
    - `it = iter(file)`
    - `print(next(it))` print the next line of the file

#### While Loops
- Will run as long as the condition is True, until a `return` is executed
- See examples

In [4]:
# will run until conditional is no longer true
mylist = []
i = 0
while len(mylist) < 11:
    mylist.append(i)
    i += 1
print(mylist)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [5]:
# will run until '4' is entered
num = 4
while True:
    inp = input("Guess a number between 1 and 5.")
    if int(inp) == num:
        print("You win!")
        print("Bye!")
        break
    elif int(inp) != num:
        print("Guess again!")

Guess a number between 1 and 5.4
You win!
Bye!


#### For Loops 
- `for i in range(data):`
    - followed by statements
    - can use `range(data)` to specify a number of times
- Lists    
    - `for i in list:` to loop through each list item
    - **Enumerating a list**
    - lets you access the index of each list value
    - `for index, var in enumerate(list):`
        - can also use `en_obj = enumerate(list)`
            - this object will contain tuples of (index, value) pairs
            - can set `start=num` to change 0 indexing
- Dictionaries
    - `for key, value in dictionary.items():`
- Can add an `else:` statement at the end to run immediately after finished

#### List Comprehensions
- List processing without using a "for loop"
- Works with **any iterable**
- Syntax
    - `new_list = [output_expression for iterator_var in iterable]`
        - `output_expression` itself can be a list comprehension

In [6]:
# simple list comprehensions
nums = [num for num in range(10)] # populate a list
print(nums)
nums_squared = [num ** 2 for num in nums] # perform arithmetic on a list
print(nums_squared)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [7]:
# nested list comprehension to create a 5x5 matrix
# unformatted, so right now is list of lists
# can convert to numpy array
matrix = [[col for col in range(0,5)] for row in range(0,5)]
print(matrix)
# convert to numpy array
np_matrix = np.array(matrix)
print(np_matrix)

[[0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4]]
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [8]:
# nested list comprehension for combining every possibility
poss_tuples = [(num1, num2) for num1 in range(0, 3) for num2 in range(4, 7)]
print(poss_tuples)

[(0, 4), (0, 5), (0, 6), (1, 4), (1, 5), (1, 6), (2, 4), (2, 5), (2, 6)]


- Conditionals with list comprehensions
    - can be placed on the output expression or the iterable

In [9]:
# list comprehension with conditional on the iterable
# square only the even numbers in this range
even_squares = [num ** 2 for num in range(11) if num % 2 == 0]
print(even_squares)

[0, 4, 16, 36, 64, 100]


In [10]:
# list comprehension with conditional on the output expression
# code doesn't run without the 'else' statement
# output is a '0' for every odd num
result = [num * 3 if num % 2 == 0 else 0 for num in range(11)]
print(result)

[0, 0, 6, 0, 12, 0, 18, 0, 24, 0, 30]


- Dictionary Comprehenions
    - use `{}` instead of `[]`
    - use `.items()` on the dictionary
    - separate key/value pairs with colon `key: value`

In [11]:
# dictionary comprehension
# use .items()
my_dict = {'a': 1, 'b': 2, 'c': 3, 'd': 4}
doubles = {key:value*2 for (key, value) in my_dict.items()}
print(doubles)

{'a': 2, 'b': 4, 'c': 6, 'd': 8}
